---
- include_tasks: setup-{{ ansible_distribution }}.yml

- include_tasks: peer.yml
  with_items: "{{ gluster_volumes }}"

- include_tasks: volume.yml
  with_items: "{{ gluster_volumes }}"

- include_tasks: mount.yml
  with_items: "{{ gluster_cluster_mounts }}"
  tags: mount