---
- include: setup-{{ ansible_distribution }}.yml

- include: peer.yml
  with_items: "{{ gluster_volumes }}"

- include: volume.yml
  with_items: "{{ gluster_volumes }}"

- include: mount.yml
  with_items: "{{ gluster_cluster_mounts }}"