---
- name: "GLUSTERFS | MOUNT | {{ item.mount }} | Create directory for glusterfs mount"
  file:
    path: "/mnt/{{ item.mount }}"
    state: directory
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"

- name: "GLUSTERFS | MOUNT | {{ item.mount }} | Mount GlusterFS on host"
  ansible.posix.mount:
    src: "localhost:/{{ item.mount }}"
    path: "/mnt/{{ item.mount }}"
    opts: defaults,_netdev
    state: mounted
    fstype: glusterfs

- name: "GLUSTERFS | MOUNT | {{ item.mount }} | Create Links Src Directory in Mount"
  file:
    path: "/mnt/{{ item.mount }}/{{ link.src }}"
    state: "directory"
    owner: "{{ link.owner }}"
    group: "{{ link.group }}"
  loop: "{{ item.links }}"
  when:
    - item.links is defined
    - item.links | length > 0
  loop_control:
    loop_var: link

- name: "GLUSTERFS | MOUNT | {{ item.mount }} | Create Links to Mount"
  file:
    src: "/mnt/{{ item.mount }}/{{ link.src }}"
    dest: "{{ link.dest }}"
    state: "{{ link.state | default('link') }}"
    owner: "{{ link.owner }}"
    group: "{{ link.group }}"
  loop: "{{ item.links }}"
  when:
    - item.links is defined
    - item.links | length > 0
  loop_control:
    loop_var: link

- name: Create cronjob to mount at reboot (workaround)
  cron:
    name: Mount all Gluster directories at boot
    special_time: reboot
    job: "mount -a"
    cron_file: gluster
    user: root