---
- name: GLUSTERFS | SETUP | Ensure dependencies are installed.
  apt:
    name:
      - gnupg2
      - apt-transport-https
      - ca-certificates
    state: present

- name: Get the DEB architecture.
  command: dpkg --print-architecture
  changed_when: false
  register: deb_architecture

- include_role:
    name: ansible-role-apt-repo
    tasks_from: repo
  vars:
    h2_apt_repos:
      - name: gluster
        repo: "https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_gpg_key_version }}/{{ glusterfs_deb_version }}/Debian/\
          {{ ansible_distribution_release }}/{{ deb_architecture.stdout }}/apt {{ ansible_distribution_release }} main"
        gpg: "https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_gpg_key_version }}/rsa.pub"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: GLUSTERFS | SETUP | Ensure GlusterFS is installed.
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present

- name: GLUSTERFS | SETUP | Ensure GlusterFS is started and enabled at boot.
  service:
    name: glusterd
    state: started
    enabled: yes
